name: 'Create a binary artifact for Node == 18 on Linux on ARM64'
description: 'Create a binary artifact for Node == 18 on Linux on ARM64 using node:18-buster'
inputs:
  node-version:
    description: 'Node.js version'
    required: false
    default: '18'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.node-version}}
